Use maximize-build-space for GH action
reichlab/covid19-forecast-hub pull request #3379
Opened 2021-03-31 13:28 UTC by Khoale1096

## Description

Use the market place maximize-build-space github action to free up ~40 GBs of space on GH action virtual environment. Closes #3244 

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

2021-03-31 14:22 UTC, hannanabdul55 approved these changes
Sounds good! @Khoale1096 - can we keep the `df --human-readable` script so that we get to see how much free space is there?

2021-03-31 14:33 UTC, ydhuang28 requested changes
Could we add back the `df --human-readable` command after the `maximize-build-space` action?

2021-03-31 15:10 UTC, Khoale1096 commented on .github/workflows/upload_to_zoltar.yml
> -      run: df --human-readable
@hannanabdul55 Yep sorry I deleted that part by accident

2021-04-06 19:49 UTC, ydhuang28 approved these changes
Looks good!

2021-04-07 12:45 UTC, merged