COVID-19Predict: Merging forecast starting at 2021-11-14
reichlab/covid19-forecast-hub pull request #5336
Opened 2021-11-14 06:01 UTC by AustinMathuw

2021-11-15 14:38 UTC, eycramer commented
Hi @AustinMathuw, 

Can you please change your  team_name to: CWRU and your model_name to: COVID-19Predict

Thanks,
Estee

2021-11-15 20:25 UTC, elray1 requested changes

2021-11-15 20:25 UTC, elray1 commented on data-processed/CWRU-COVID_19Predict/metadata-CWRU-COVID_19Predict.txt
> +team_name: COVID-19Predict
```suggestion
team_name: CWRU
```

2021-11-15 20:25 UTC, elray1 commented on data-processed/CWRU-COVID_19Predict/metadata-CWRU-COVID_19Predict.txt
> +model_name: Dynamic 7-day Short-Term Predictions
```suggestion
model_name: COVID_19Predict
```

2021-11-15 20:26 UTC, elray1 approved these changes

2021-11-15 20:27 UTC, merged

2021-11-16 12:55 UTC, AustinMathuw commented
Thank you @elray1 for doing the changes!